CREATE TABLE `hardware_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceCode` varchar(32) NOT NULL,
	`teamNameCipher` varchar(1024) NOT NULL,
	`leadNameCipher` varchar(1024) NOT NULL,
	`emailCipher` varchar(1024) NOT NULL,
	`phoneCipher` varchar(1024) NOT NULL,
	`collegeCipher` varchar(1024) NOT NULL,
	`memberOneCipher` varchar(1024) NOT NULL,
	`memberTwoCipher` varchar(1024) NOT NULL,
	`memberThreeCipher` varchar(1024),
	`memberFourCipher` varchar(1024),
	`memberCount` int NOT NULL,
	`domain` varchar(96) NOT NULL,
	`transactionCipher` varchar(1024) NOT NULL,
	`transactionFingerprint` varchar(64) NOT NULL,
	`paymentStatus` enum('payment_pending','verified','rejected') NOT NULL DEFAULT 'payment_pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `hardware_registrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `hardware_registrations_referenceCode_unique` UNIQUE(`referenceCode`),
	CONSTRAINT `hardware_registrations_transactionFingerprint_unique` UNIQUE(`transactionFingerprint`)
);
--> statement-breakpoint
CREATE TABLE `software_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceCode` varchar(32) NOT NULL,
	`teamNameCipher` varchar(1024) NOT NULL,
	`leadNameCipher` varchar(1024) NOT NULL,
	`emailCipher` varchar(1024) NOT NULL,
	`phoneCipher` varchar(1024) NOT NULL,
	`collegeCipher` varchar(1024) NOT NULL,
	`memberOneCipher` varchar(1024) NOT NULL,
	`memberTwoCipher` varchar(1024) NOT NULL,
	`memberThreeCipher` varchar(1024),
	`memberFourCipher` varchar(1024),
	`memberCount` int NOT NULL,
	`domain` varchar(96) NOT NULL,
	`transactionCipher` varchar(1024) NOT NULL,
	`transactionFingerprint` varchar(64) NOT NULL,
	`paymentStatus` enum('payment_pending','verified','rejected') NOT NULL DEFAULT 'payment_pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `software_registrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `software_registrations_referenceCode_unique` UNIQUE(`referenceCode`),
	CONSTRAINT `software_registrations_transactionFingerprint_unique` UNIQUE(`transactionFingerprint`)
);
